CFLAGS += -std=c99 -O0

PROGRAM = detection_invalidation
SOURCE  = detection_invalidation.c

all: $(PROGRAM)

$(PROGRAM): $(SOURCE) ; $(CC) $(CFLAGS) -o $(PROGRAM) $(SOURCE)

clean: ; rm -f $(PROGRAM)
